// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvgiVlJ0jj_0AneMl1qm2LUoFoT4VF_l4',
    appId: '1:392167869639:web:a9259ddd605ee03c74c2e2',
    messagingSenderId: '392167869639',
    projectId: 'geoprova-app',
    authDomain: 'geoprova-app.firebaseapp.com',
    storageBucket: 'geoprova-app.appspot.com',
    measurementId: 'G-C3DG54FN5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGBEbASPhfIdTduTVpLSEFfgO1HKMPzsU',
    appId: '1:392167869639:android:57e045c85edaafa874c2e2',
    messagingSenderId: '392167869639',
    projectId: 'geoprova-app',
    storageBucket: 'geoprova-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Whv0KdChpOy2KhQD4EAMYq1IPZOKC0M',
    appId: '1:392167869639:ios:4e05a6e0e58b3c2074c2e2',
    messagingSenderId: '392167869639',
    projectId: 'geoprova-app',
    storageBucket: 'geoprova-app.appspot.com',
    iosBundleId: 'com.example.projectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Whv0KdChpOy2KhQD4EAMYq1IPZOKC0M',
    appId: '1:392167869639:ios:7890194648a1a81e74c2e2',
    messagingSenderId: '392167869639',
    projectId: 'geoprova-app',
    storageBucket: 'geoprova-app.appspot.com',
    iosBundleId: 'com.example.projectTest.RunnerTests',
  );
}
